**Setting up**

In [3]:
import pandas as pd
import os
from dotenv import load_dotenv

In [4]:
# Connecting sql via pandas using sqlalchemy

from sqlalchemy import create_engine

load_dotenv()
DB_STRING = os.getenv("DB_STRING")

if DB_STRING is None:
    raise ValueError("DB_STRING is not set in the environment.")

db = create_engine(DB_STRING)

In [5]:
# Query King County housing sales joined with house details, and load into a DataFrame
query_string = """
select *
FROM eda.king_county_house_sales AS t2
LEFT JOIN eda.king_county_house_details AS t1
ON t2.house_id = t1. id;
"""

df = pd.read_sql(query_string, db)
df.head()

,date,price,house_id,id,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2014-10-13,221900.0,7129300520,1,7129300520,3.0,1.00,1180.0,5650.0,1.0,...,7,1180.0,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0
1,2014-12-09,538000.0,6414100192,2,6414100192,3.0,2.25,2570.0,7242.0,2.0,...,7,2170.0,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0
2,2015-02-25,180000.0,5631500400,3,5631500400,2.0,1.00,770.0,10000.0,1.0,...,6,770.0,0.0,1933,NaN,98028,47.7379,-122.233,2720.0,8062.0
3,2014-12-09,604000.0,2487200875,4,2487200875,4.0,3.00,1960.0,5000.0,1.0,...,7,1050.0,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0
4,2015-02-18,510000.0,1954400510,5,1954400510,3.0,2.00,1680.0,8080.0,1.0,...,8,1680.0,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0

In [6]:
# save as CSV
df.to_csv("data/king_county_house.csv", index=False)

**Having an overview of a data**

In [8]:
df. shape   # count row, column

(21597, 23)

In [9]:
df.head()   # having a quick overview of data

# -> overlapping columns (id)

,date,price,house_id,id,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2014-10-13,221900.0,7129300520,1,7129300520,3.0,1.00,1180.0,5650.0,1.0,...,7,1180.0,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0
1,2014-12-09,538000.0,6414100192,2,6414100192,3.0,2.25,2570.0,7242.0,2.0,...,7,2170.0,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0
2,2015-02-25,180000.0,5631500400,3,5631500400,2.0,1.00,770.0,10000.0,1.0,...,6,770.0,0.0,1933,NaN,98028,47.7379,-122.233,2720.0,8062.0
3,2014-12-09,604000.0,2487200875,4,2487200875,4.0,3.00,1960.0,5000.0,1.0,...,7,1050.0,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0
4,2015-02-18,510000.0,1954400510,5,1954400510,3.0,2.00,1680.0,8080.0,1.0,...,8,1680.0,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0

In [10]:
df.info() # types of each column, info of null

# -> columns that have null : waterfront, view, sqft_basement, yr_renovated

# -> continuous columns : price, bedrooms, bathrooms, sqft_living, sqft_lot, floors, sqft_above, sqft_basement, yr_built, lat, long ,sqft_living15, sqft_lot15

# -> categorical coloumns : house_id, id, id.1, waterfront, view, condition, grade, zipcode

# -> date : date (will convert it into datetime type)

<class 'pandas.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           21597 non-null  object
 1   price          21597 non-null  float64
 2   house_id       21597 non-null  int64
 3   id             21597 non-null  int64
 4   id             21597 non-null  int64
 5   bedrooms       21597 non-null  float64
 6   bathrooms      21597 non-null  float64
 7   sqft_living    21597 non-null  float64
 8   sqft_lot       21597 non-null  float64
 9   floors         21597 non-null  float64
 10  waterfront     19206 non-null  float64
 11  view           21534 non-null  float64
 12  condition      21597 non-null  int64
 13  grade          21597 non-null  int64
 14  sqft_above     21597 non-null  float64
 15  sqft_basement  21145 non-null  float64
 16  yr_built       21597 non-null  int64
 17  yr_renovated   17749 non-null  float64
 18  zipcode        21597 non-null  int64
 19  lat            21597 non-null  float64
 20  long           21597 non-null  float64
 21  sqft_living15  21597 non-null  float64
 22  sqft_lot15     21597 non-null  float64
dtypes: float64(15), int64(7), object(1)
memory usage: 3.8+ MB

In [11]:
df.describe()
#-> house with 33 rooms? is it actually a huge mension, or false data?
#-> sqft_lot == 1651359.0 seems like a huge land.

,price,house_id,id,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.159700e+04,2.159700e+04,21597.000000,2.159700e+04,21597.000000,21597.000000,21597.000000,2.159700e+04,21597.000000,19206.000000,...,21597.000000,21597.000000,21145.000000,21597.000000,17749.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000
mean,5.402966e+05,4.580474e+09,10799.000000,4.580474e+09,3.373200,2.115826,2080.321850,1.509941e+04,1.494096,0.007602,...,7.657915,1788.596842,291.857224,1970.999676,836.650516,98077.951845,47.560093,-122.213983,1986.620318,12758.283512
std,3.673681e+05,2.876736e+09,6234.661218,2.876736e+09,0.926299,0.768984,918.106125,4.141264e+04,0.539683,0.086858,...,1.173200,827.759761,442.490863,29.375234,4000.110554,53.513072,0.138552,0.140724,685.230472,27274.441950
min,7.800000e+04,1.000102e+06,1.000000,1.000102e+06,1.000000,0.500000,370.000000,5.200000e+02,1.000000,0.000000,...,3.000000,370.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,3.220000e+05,2.123049e+09,5400.000000,2.123049e+09,3.000000,1.750000,1430.000000,5.040000e+03,1.000000,0.000000,...,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471100,-122.328000,1490.000000,5100.000000
50%,4.500000e+05,3.904930e+09,10799.000000,3.904930e+09,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,...,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.231000,1840.000000,7620.000000
75%,6.450000e+05,7.308900e+09,16198.000000,7.308900e+09,4.000000,2.500000,2550.000000,1.068500e+04,2.000000,0.000000,...,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,7.700000e+06,9.900000e+09,21597.000000,9.900000e+09,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,...,13.000000,9410.000000,4820.000000,2015.000000,20150.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [12]:
# restart every time I reopen this note
import pandas as pd

df = pd.read_csv("data/king_county_house.csv")
df

,date,price,house_id,id,id.1,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2014-10-13,221900.0,7129300520,1,7129300520,3.0,1.00,1180.0,5650.0,1.0,...,7,1180.0,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0
1,2014-12-09,538000.0,6414100192,2,6414100192,3.0,2.25,2570.0,7242.0,2.0,...,7,2170.0,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0
2,2015-02-25,180000.0,5631500400,3,5631500400,2.0,1.00,770.0,10000.0,1.0,...,6,770.0,0.0,1933,NaN,98028,47.7379,-122.233,2720.0,8062.0
3,2014-12-09,604000.0,2487200875,4,2487200875,4.0,3.00,1960.0,5000.0,1.0,...,7,1050.0,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0
4,2015-02-18,510000.0,1954400510,5,1954400510,3.0,2.00,1680.0,8080.0,1.0,...,8,1680.0,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21592,2014-05-21,360000.0,263000018,21593,263000018,3.0,2.50,1530.0,1131.0,3.0,...,8,1530.0,0.0,2009,0.0,98103,47.6993,-122.346,1530.0,1509.0
21593,2015-02-23,400000.0,6600060120,21594,6600060120,4.0,2.50,2310.0,5813.0,2.0,...,8,2310.0,0.0,2014,0.0,98146,47.5107,-122.362,1830.0,7200.0
21594,2014-06-23,402101.0,1523300141,21595,1523300141,2.0,0.75,1020.0,1350.0,2.0,...,7,1020.0,0.0,2009,0.0,98144,47.5944,-122.299,1020.0,2007.0
21595,2015-01-16,400000.0,291310100,21596,291310100,3.0,2.50,1600.0,2388.0,2.0,...,8,1600.0,0.0,2004,0.0,98027,47.5345,-122.069,1410.0,1287.0
21596,2014-10-15,325000.0,1523300157,21597,1523300157,2.0,0.75,1020.0,1076.0,2.0,...,7,1020.0,0.0,2008,0.0,98144,47.5941,-122.299,1020.0,1357.0

**Data Cleaning**

Outliers

In [13]:
# checking details of the house that has 33 rooms 
df[df["bedrooms"] == 33]
# turn out to be outlier (the house has only "1.75" bathroom)

,date,price,house_id,id,id.1,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
15856,2014-06-25,640000.0,2402100895,15857,2402100895,33.0,1.75,1620.0,6000.0,1.0,...,7,1040.0,580.0,1947,0.0,98103,47.6878,-122.331,1330.0,4700.0

In [14]:
# deleting the row with 33 rooms

df = df[df["bedrooms"] != 33]

In [ ]:
# checking details of the house that has sqft_lot == 1651359.0
df[df["sqft_lot"] == 1651359.0]

#-> other numbers seem reasonable, and the area is a big farming area, which explains the large lot for the houses nearby.

,date,price,house_id,id,id.1,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
1717,2015-03-27,700000.0,1020069017,1718,1020069017,4.0,1.0,1300.0,1651359.0,1.0,...,6,1300.0,0.0,1920,0.0,98022,47.2313,-122.023,2560.0,425581.0

In [ ]:
# taking care of 2x id columns
# checking the list of column

df.columns.tolist()

['date',
 'price',
 'house_id',
 'id',
 'id.1',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long',
 'sqft_living15',
 'sqft_lot15']

In [15]:
#deleting the id column
df = df.drop(columns=["id.1"])
df.head()

,date,price,house_id,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2014-10-13,221900.0,7129300520,1,3.0,1.00,1180.0,5650.0,1.0,NaN,...,7,1180.0,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0
1,2014-12-09,538000.0,6414100192,2,3.0,2.25,2570.0,7242.0,2.0,0.0,...,7,2170.0,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0
2,2015-02-25,180000.0,5631500400,3,2.0,1.00,770.0,10000.0,1.0,0.0,...,6,770.0,0.0,1933,NaN,98028,47.7379,-122.233,2720.0,8062.0
3,2014-12-09,604000.0,2487200875,4,4.0,3.00,1960.0,5000.0,1.0,0.0,...,7,1050.0,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0
4,2015-02-18,510000.0,1954400510,5,3.0,2.00,1680.0,8080.0,1.0,0.0,...,8,1680.0,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0

**Dealing with Duplicates**

In [16]:
df.shape

(21596, 22)

In [17]:
#checking duplicate count (row)
df.duplicated().value_counts()

# no duplicates

False    21596
Name: count, dtype: int64

**Data Types and Transforming Data**

In [18]:
df.dtypes

#-> overall looks good (no mixed types. object)
#-> will change date into datetime, so it will be possible to compare

date                 str
price            float64
house_id           int64
id                 int64
bedrooms         float64
bathrooms        float64
sqft_living      float64
sqft_lot         float64
floors           float64
waterfront       float64
view             float64
condition          int64
grade              int64
sqft_above       float64
sqft_basement    float64
yr_built           int64
yr_renovated     float64
zipcode            int64
lat              float64
long             float64
sqft_living15    float64
sqft_lot15       float64
dtype: object

In [ ]:
#converting date to datetime
df["date"] = pd.to_datetime(df["date"], format="%Y-%m-%d")

In [39]:
df.head()

,date,price,house_id,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2014-10-13,221900.0,7129300520,1,3.0,1.00,1180.0,5650.0,1.0,0.0,...,7,1180.0,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0
1,2014-12-09,538000.0,6414100192,2,3.0,2.25,2570.0,7242.0,2.0,0.0,...,7,2170.0,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0
2,2015-02-25,180000.0,5631500400,3,2.0,1.00,770.0,10000.0,1.0,0.0,...,6,770.0,0.0,1933,0.0,98028,47.7379,-122.233,2720.0,8062.0
3,2014-12-09,604000.0,2487200875,4,4.0,3.00,1960.0,5000.0,1.0,0.0,...,7,1050.0,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0
4,2015-02-18,510000.0,1954400510,5,3.0,2.00,1680.0,8080.0,1.0,0.0,...,8,1680.0,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0

**Dealing with Missing Values**

1. Waterfront

In [21]:
#counting missing values per column

df.isna().sum()

date                0
price               0
house_id            0
id                  0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront       2391
view               63
condition           0
grade               0
sqft_above          0
sqft_basement     452
yr_built            0
yr_renovated     3848
zipcode             0
lat                 0
long                0
sqft_living15       0
sqft_lot15          0
dtype: int64

In [ ]:
# missing values in waterfront(2391): probably forgot to write 0
# compare the housing price to the price of waterfront housing before replace the missing cells with 0

In [23]:
# 1) Check price stats for houses with missing (NaN) waterfront value
df[df["waterfront"].isna()]["price"].agg(["count", "mean", "median"])

count       2391.000000
mean      528420.124216
median    445000.000000
Name: price, dtype: float64

In [ ]:
# 2) Check price stats for houses with waterfront = 1 (has waterfront)
df[df["waterfront"] == 1]["price"].agg(["count", "mean", "median"])

count     1.460000e+02
mean      1.717215e+06
median    1.510000e+06
Name: price, dtype: float64

In [ ]:
# 3) Check price stats for houses with waterfront = 0 (no waterfront)
df[df["waterfront"] == 0]["price"].agg(["count", "mean", "median"])

count      19059.000000
mean      532765.582192
median    450000.000000
Name: price, dtype: float64

In [24]:
# All three groups (missing data, waterfront 0/1) together (missing values included as their own group)
df.groupby(df["waterfront"], dropna=False)["price"].agg(["count", "mean", "median"])

#-> average values of missling values are close to the ones of 0.

            count          mean     median
waterfront
0.0         19059  5.327656e+05   450000.0
1.0           146  1.717215e+06  1510000.0
NaN          2391  5.284201e+05   445000.0

In [25]:
#replacing the empty cell with 0
df = df.fillna({"waterfront": 0})

In [26]:
#count the missing values in waterfront
df["waterfront"].isna().sum()

np.int64(0)

2. View

In [27]:
#count the empty cells in view : 0
df["view"].isna().sum()

np.int64(63)

In [28]:
# 63 is only 0.29 % of total -> delete them, or replace them with 0
#replacing the empty cell with 0
df = df.fillna({"view": 0})

3. yr_renovated

Assumption 1. They forgot to put 0 

Assumption 2. The houses that are not renovated are mostly built recently

In [29]:
# Checking the average missing values of year of the house built
df[df["yr_renovated"].isna()]["yr_built"].agg(["count", "mean", "median"])

# -> mean and median is more less similar, which means the average year_built is somewhere 1970 (apposite to my assumption)

count     3848.000000
mean      1970.390593
median    1973.000000
Name: yr_built, dtype: float64

In [30]:
#I decided that missing value in yr_renovated should be 0, 
# because there could be other reasons why the history of renovation was not updated. (e.g. partial renovation)
# I think keeping the data as 0 is more reasonble than deleting them

# replacing the empty cell with 0

df = df.fillna({"yr_renovated": 0})

In [31]:
df["yr_renovated"].isna().sum()

np.int64(0)

3. Basement

In [32]:
# does missing data in sqft_basement mean those are houses without basement?
# If that is the case, sqft_living = sqft_above
df[df["sqft_basement"].isna()][["sqft_living", "sqft_above"]].head(452)

# -> some of them match, some not

       sqft_living  sqft_above
6           1715.0      1715.0
18          1200.0      1200.0
42          3595.0      3595.0
79          3450.0      3450.0
112         1540.0      1160.0
...            ...         ...
21442       2360.0      1390.0
21447       2330.0      2330.0
21473        980.0       980.0
21519       2380.0      2380.0
21581       3410.0      3410.0

[452 rows x 2 columns]

In [33]:
# basement = sqft_living - sqft_above

df["sqft_basement"] = df["sqft_basement"].fillna(df["sqft_living"] - df["sqft_above"])
df["sqft_basement"].isna().sum()

np.int64(0)

Rounding data

In [42]:
# rounding data
df["price"] = df.price.round(0)
df["floors"] = df.floors.round(2)
df["bathrooms"] = df.bathrooms.round(3)


df.head(10)

,date,price,house_id,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2014-10-13,221900.0,7129300520,1,3.0,1.00,1180.0,5650.0,1.0,0.0,...,7,1180.0,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0
1,2014-12-09,538000.0,6414100192,2,3.0,2.25,2570.0,7242.0,2.0,0.0,...,7,2170.0,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0
2,2015-02-25,180000.0,5631500400,3,2.0,1.00,770.0,10000.0,1.0,0.0,...,6,770.0,0.0,1933,0.0,98028,47.7379,-122.233,2720.0,8062.0
3,2014-12-09,604000.0,2487200875,4,4.0,3.00,1960.0,5000.0,1.0,0.0,...,7,1050.0,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0
4,2015-02-18,510000.0,1954400510,5,3.0,2.00,1680.0,8080.0,1.0,0.0,...,8,1680.0,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0
5,2014-05-12,1230000.0,7237550310,6,4.0,4.50,5420.0,101930.0,1.0,0.0,...,11,3890.0,1530.0,2001,0.0,98053,47.6561,-122.005,4760.0,101930.0
6,2014-06-27,257500.0,1321400060,7,3.0,2.25,1715.0,6819.0,2.0,0.0,...,7,1715.0,0.0,1995,0.0,98003,47.3097,-122.327,2238.0,6819.0
7,2015-01-15,291850.0,2008000270,8,3.0,1.50,1060.0,9711.0,1.0,0.0,...,7,1060.0,0.0,1963,0.0,98198,47.4095,-122.315,1650.0,9711.0
8,2015-04-15,229500.0,2414600126,9,3.0,1.00,1780.0,7470.0,1.0,0.0,...,7,1050.0,730.0,1960,0.0,98146,47.5123,-122.337,1780.0,8113.0
9,2015-03-12,323000.0,3793500160,10,3.0,2.50,1890.0,6560.0,2.0,0.0,...,7,1890.0,0.0,2003,0.0,98038,47.3684,-122.031,2390.0,7570.0

In [43]:
# Convert Zipcode into Integer 
df["zipcode"] = df["zipcode"].astype(int)
df.head()

,date,price,house_id,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2014-10-13,221900.0,7129300520,1,3.0,1.00,1180.0,5650.0,1.0,0.0,...,7,1180.0,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0
1,2014-12-09,538000.0,6414100192,2,3.0,2.25,2570.0,7242.0,2.0,0.0,...,7,2170.0,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0
2,2015-02-25,180000.0,5631500400,3,2.0,1.00,770.0,10000.0,1.0,0.0,...,6,770.0,0.0,1933,0.0,98028,47.7379,-122.233,2720.0,8062.0
3,2014-12-09,604000.0,2487200875,4,4.0,3.00,1960.0,5000.0,1.0,0.0,...,7,1050.0,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0
4,2015-02-18,510000.0,1954400510,5,3.0,2.00,1680.0,8080.0,1.0,0.0,...,8,1680.0,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0

In [44]:
# Save the cleaned dataset 
df.to_csv("data/king_county_house_cleaned.csv", index=False)