Setting up

In [1]:
import pandas as pd
import os
from dotenv import load_dotenv

In [2]:
#Connecting sql via pandas using sqlalchemy

from sqlalchemy import create_engine

load_dotenv()
DB_STRING = os.getenv("DB_STRING")

if DB_STRING is None:
    raise ValueError("DB_STRING is not set in the environment.")

db = create_engine(DB_STRING)

In [3]:
query_string = """
select *
FROM eda.king_county_house_sales AS t2
LEFT JOIN eda.king_county_house_details AS t1
ON t2.house_id = t1. id;
"""

df = pd.read_sql(query_string, db)
df.head()

,date,price,house_id,id,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2014-10-13,221900.0,7129300520,1,7129300520,3.0,1.00,1180.0,5650.0,1.0,...,7,1180.0,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0
1,2014-12-09,538000.0,6414100192,2,6414100192,3.0,2.25,2570.0,7242.0,2.0,...,7,2170.0,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0
2,2015-02-25,180000.0,5631500400,3,5631500400,2.0,1.00,770.0,10000.0,1.0,...,6,770.0,0.0,1933,NaN,98028,47.7379,-122.233,2720.0,8062.0
3,2014-12-09,604000.0,2487200875,4,2487200875,4.0,3.00,1960.0,5000.0,1.0,...,7,1050.0,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0
4,2015-02-18,510000.0,1954400510,5,1954400510,3.0,2.00,1680.0,8080.0,1.0,...,8,1680.0,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0

In [4]:
df.to_csv("data/king_county_house.csv", index=False)

In [5]:
df.shape          # 행/열 개수 확인
df.head()         # 다시 한번 데이터 훑어보기
df.info()         # 컬럼별 타입, 결측치 유무
df.describe()     # 숫자 컬럼 통계 요약

<class 'pandas.DataFrame'>
RangeIndex: 21597 entries, 0 to 21596
Data columns (total 23 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           21597 non-null  object
 1   price          21597 non-null  float64
 2   house_id       21597 non-null  int64
 3   id             21597 non-null  int64
 4   id             21597 non-null  int64
 5   bedrooms       21597 non-null  float64
 6   bathrooms      21597 non-null  float64
 7   sqft_living    21597 non-null  float64
 8   sqft_lot       21597 non-null  float64
 9   floors         21597 non-null  float64
 10  waterfront     19206 non-null  float64
 11  view           21534 non-null  float64
 12  condition      21597 non-null  int64
 13  grade          21597 non-null  int64
 14  sqft_above     21597 non-null  float64
 15  sqft_basement  21145 non-null  float64
 16  yr_built       21597 non-null  int64
 17  yr_renovated   17749 non-null  float64
 18  zipcode        21597 non-null  int64
 19  lat            21597 non-null  float64
 20  long           21597 non-null  float64
 21  sqft_living15  21597 non-null  float64
 22  sqft_lot15     21597 non-null  float64
dtypes: float64(15), int64(7), object(1)
memory usage: 3.8+ MB

,price,house_id,id,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.159700e+04,2.159700e+04,21597.000000,2.159700e+04,21597.000000,21597.000000,21597.000000,2.159700e+04,21597.000000,19206.000000,...,21597.000000,21597.000000,21145.000000,21597.000000,17749.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000
mean,5.402966e+05,4.580474e+09,10799.000000,4.580474e+09,3.373200,2.115826,2080.321850,1.509941e+04,1.494096,0.007602,...,7.657915,1788.596842,291.857224,1970.999676,836.650516,98077.951845,47.560093,-122.213983,1986.620318,12758.283512
std,3.673681e+05,2.876736e+09,6234.661218,2.876736e+09,0.926299,0.768984,918.106125,4.141264e+04,0.539683,0.086858,...,1.173200,827.759761,442.490863,29.375234,4000.110554,53.513072,0.138552,0.140724,685.230472,27274.441950
min,7.800000e+04,1.000102e+06,1.000000,1.000102e+06,1.000000,0.500000,370.000000,5.200000e+02,1.000000,0.000000,...,3.000000,370.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,3.220000e+05,2.123049e+09,5400.000000,2.123049e+09,3.000000,1.750000,1430.000000,5.040000e+03,1.000000,0.000000,...,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471100,-122.328000,1490.000000,5100.000000
50%,4.500000e+05,3.904930e+09,10799.000000,3.904930e+09,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,...,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.231000,1840.000000,7620.000000
75%,6.450000e+05,7.308900e+09,16198.000000,7.308900e+09,4.000000,2.500000,2550.000000,1.068500e+04,2.000000,0.000000,...,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,7.700000e+06,9.900000e+09,21597.000000,9.900000e+09,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,...,13.000000,9410.000000,4820.000000,2015.000000,20150.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [6]:
df. shape

(21597, 23)

In [7]:
df.head()

,date,price,house_id,id,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2014-10-13,221900.0,7129300520,1,7129300520,3.0,1.00,1180.0,5650.0,1.0,...,7,1180.0,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0
1,2014-12-09,538000.0,6414100192,2,6414100192,3.0,2.25,2570.0,7242.0,2.0,...,7,2170.0,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0
2,2015-02-25,180000.0,5631500400,3,5631500400,2.0,1.00,770.0,10000.0,1.0,...,6,770.0,0.0,1933,NaN,98028,47.7379,-122.233,2720.0,8062.0
3,2014-12-09,604000.0,2487200875,4,2487200875,4.0,3.00,1960.0,5000.0,1.0,...,7,1050.0,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0
4,2015-02-18,510000.0,1954400510,5,1954400510,3.0,2.00,1680.0,8080.0,1.0,...,8,1680.0,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0

In [8]:
df

,date,price,house_id,id,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2014-10-13,221900.0,7129300520,1,7129300520,3.0,1.00,1180.0,5650.0,1.0,...,7,1180.0,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0
1,2014-12-09,538000.0,6414100192,2,6414100192,3.0,2.25,2570.0,7242.0,2.0,...,7,2170.0,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0
2,2015-02-25,180000.0,5631500400,3,5631500400,2.0,1.00,770.0,10000.0,1.0,...,6,770.0,0.0,1933,NaN,98028,47.7379,-122.233,2720.0,8062.0
3,2014-12-09,604000.0,2487200875,4,2487200875,4.0,3.00,1960.0,5000.0,1.0,...,7,1050.0,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0
4,2015-02-18,510000.0,1954400510,5,1954400510,3.0,2.00,1680.0,8080.0,1.0,...,8,1680.0,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21592,2014-05-21,360000.0,263000018,21593,263000018,3.0,2.50,1530.0,1131.0,3.0,...,8,1530.0,0.0,2009,0.0,98103,47.6993,-122.346,1530.0,1509.0
21593,2015-02-23,400000.0,6600060120,21594,6600060120,4.0,2.50,2310.0,5813.0,2.0,...,8,2310.0,0.0,2014,0.0,98146,47.5107,-122.362,1830.0,7200.0
21594,2014-06-23,402101.0,1523300141,21595,1523300141,2.0,0.75,1020.0,1350.0,2.0,...,7,1020.0,0.0,2009,0.0,98144,47.5944,-122.299,1020.0,2007.0
21595,2015-01-16,400000.0,291310100,21596,291310100,3.0,2.50,1600.0,2388.0,2.0,...,8,1600.0,0.0,2004,0.0,98027,47.5345,-122.069,1410.0,1287.0
21596,2014-10-15,325000.0,1523300157,21597,1523300157,2.0,0.75,1020.0,1076.0,2.0,...,7,1020.0,0.0,2008,0.0,98144,47.5941,-122.299,1020.0,1357.0

In [9]:
import pandas as pd

df = pd.read_csv("data/king_county_house.csv")
df

,date,price,house_id,id,id.1,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,2014-10-13,221900.0,7129300520,1,7129300520,3.0,1.00,1180.0,5650.0,1.0,...,7,1180.0,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0
1,2014-12-09,538000.0,6414100192,2,6414100192,3.0,2.25,2570.0,7242.0,2.0,...,7,2170.0,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0
2,2015-02-25,180000.0,5631500400,3,5631500400,2.0,1.00,770.0,10000.0,1.0,...,6,770.0,0.0,1933,NaN,98028,47.7379,-122.233,2720.0,8062.0
3,2014-12-09,604000.0,2487200875,4,2487200875,4.0,3.00,1960.0,5000.0,1.0,...,7,1050.0,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0
4,2015-02-18,510000.0,1954400510,5,1954400510,3.0,2.00,1680.0,8080.0,1.0,...,8,1680.0,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21592,2014-05-21,360000.0,263000018,21593,263000018,3.0,2.50,1530.0,1131.0,3.0,...,8,1530.0,0.0,2009,0.0,98103,47.6993,-122.346,1530.0,1509.0
21593,2015-02-23,400000.0,6600060120,21594,6600060120,4.0,2.50,2310.0,5813.0,2.0,...,8,2310.0,0.0,2014,0.0,98146,47.5107,-122.362,1830.0,7200.0
21594,2014-06-23,402101.0,1523300141,21595,1523300141,2.0,0.75,1020.0,1350.0,2.0,...,7,1020.0,0.0,2009,0.0,98144,47.5944,-122.299,1020.0,2007.0
21595,2015-01-16,400000.0,291310100,21596,291310100,3.0,2.50,1600.0,2388.0,2.0,...,8,1600.0,0.0,2004,0.0,98027,47.5345,-122.069,1410.0,1287.0
21596,2014-10-15,325000.0,1523300157,21597,1523300157,2.0,0.75,1020.0,1076.0,2.0,...,7,1020.0,0.0,2008,0.0,98144,47.5941,-122.299,1020.0,1357.0


| Nicole Johnson      | Buyer  | Lively, central neighborhood, middle price range, right timing (within a year) 

1. Does the house density in that area affect the price of the house?
Hypothesis: House price is not affected by house density directly, but rather by scarse and high-value feature such as waterfront or how close it is to central.

2. Does the proximity to Seattle downtown affect the price of the house?
Hypothesis: The proximity has significant impact on the housing price

3. Does the time of the year (season/month) affect the price of the house?
Hypothesis: Specific season (Summer months) have both a higher number of listings and higher average/median prices compared to other seasons

In [38]:
zipcode_counts = df.groupby("zipcode").agg(
house_count=("zipcode", "size"),
avg_price=("price", "mean"),
median_price=("price", "median")
).reset_index()

zipcode_counts = zipcode_counts.sort_values("house_count", ascending=False)
zipcode_counts.head(30)

    zipcode  house_count     avg_price  median_price
42    98103          602  5.850488e+05      550000.0
23    98038          589  3.670915e+05      342000.0
49    98115          583  6.199441e+05      567000.0
28    98052          574  6.452442e+05      615000.0
51    98117          553  5.768348e+05      544000.0
26    98042          547  3.115803e+05      291500.0
22    98034          545  5.217400e+05      445950.0
52    98118          507  4.180194e+05      367500.0
13    98023          499  2.867428e+05      268450.0
5     98006          498  8.599386e+05      760184.5
57    98133          493  3.870116e+05      375000.0
33    98059          468  4.936253e+05      435000.0
32    98058          455  3.536191e+05      335000.0
62    98155          446  4.237369e+05      375000.0
37    98074          441  6.856758e+05      642000.0
21    98033          432  8.039908e+05      678350.0
15    98027          412  6.170540e+05      570500.0
55    98125          409  4.699288e+05      425000.0
31    98056          406  4.208955e+05      380000.0
29    98053          403  6.772150e+05      635000.0
0     98001          361  2.811949e+05      260000.0
38    98075          359  7.907347e+05      739999.0
56    98126          354  4.247346e+05      395750.0
40    98092          351  3.349211e+05      309780.0
59    98144          343  5.947065e+05      450000.0
44    98106          335  3.195814e+05      315000.0
50    98116          330  6.186951e+05      562750.0
17    98029          321  6.126427e+05      575000.0
69    98199          317  7.921879e+05      689800.0
3     98004          317  1.356524e+06     1150000.0

In [39]:
df["price"].describe()

count    2.159700e+04
mean     5.402966e+05
std      3.673681e+05
min      7.800000e+04
25%      3.220000e+05
50%      4.500000e+05
75%      6.450000e+05
max      7.700000e+06
Name: price, dtype: float64

In [40]:
#corelation between waterfront and houseprice

df.groupby("waterfront")["price"].agg(["count", "mean", "median"])

            count          mean     median
waterfront
0.0         19060  5.327712e+05   450000.0
1.0           146  1.717215e+06  1510000.0

In [41]:
# name of coloumns
df.columns.tolist()

['date',
 'price',
 'house_id',
 'id',
 'id.1',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long',
 'sqft_living15',
 'sqft_lot15']

In [42]:
seattle_lat = 47.6062
seattle_long = -122.3321

df["distance_to_downtown"] = ((df["lat"] - seattle_lat)**2 + (df["long"] - seattle_long)**2)**0.5

df["distance_to_downtown"].corr(df["price"])

np.float64(-0.19132362353839297)

In [43]:
df.groupby("date")["price"].agg(["count", "mean", "median"])

            count          mean     median
date
2014-05-02     67  5.261918e+05   445700.0
2014-05-03      4  4.669700e+05   466440.0
2014-05-04      5  5.766900e+05   628000.0
2014-05-05     84  5.810577e+05   536062.5
2014-05-06     83  5.341684e+05   483500.0
...           ...           ...        ...
2015-05-13     31  5.116239e+05   419950.0
2015-05-14     11  6.038908e+05   456500.0
2015-05-15      1  4.500000e+05   450000.0
2015-05-24      1  4.455000e+05   445500.0
2015-05-27      1  1.310000e+06  1310000.0

[372 rows x 3 columns]

In [44]:
# trying to get the housing price per month, not per date
# 1. change date into datetime
df["date"] = pd.to_datetime(df["date"])

In [45]:
#2. creat a new column based on Month
df["sale_month"] = df["date"].dt.month

df.head(15)

,date,price,house_id,id,id.1,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,distance_to_downtown,sale_month
0,2014-10-13,221900.0,7129300520,1,7129300520,3.0,1.00,1180.0,5650.0,1.0,...,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0,0.121099,10
1,2014-12-09,538000.0,6414100192,2,6414100192,3.0,2.25,2570.0,7242.0,2.0,...,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0,0.115545,12
2,2015-02-25,180000.0,5631500400,3,5631500400,2.0,1.00,770.0,10000.0,1.0,...,0.0,1933,NaN,98028,47.7379,-122.233,2720.0,8062.0,0.164820,2
3,2014-12-09,604000.0,2487200875,4,2487200875,4.0,3.00,1960.0,5000.0,1.0,...,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0,0.104890,12
4,2015-02-18,510000.0,1954400510,5,1954400510,3.0,2.00,1680.0,8080.0,1.0,...,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0,0.287296,2
5,2014-05-12,1230000.0,7237550310,6,7237550310,4.0,4.50,5420.0,101930.0,1.0,...,1530.0,2001,0.0,98053,47.6561,-122.005,4760.0,101930.0,0.330884,5
6,2014-06-27,257500.0,1321400060,7,1321400060,3.0,2.25,1715.0,6819.0,2.0,...,NaN,1995,0.0,98003,47.3097,-122.327,2238.0,6819.0,0.296544,6
7,2015-01-15,291850.0,2008000270,8,2008000270,3.0,1.50,1060.0,9711.0,1.0,...,0.0,1963,0.0,98198,47.4095,-122.315,1650.0,9711.0,0.197442,1
8,2015-04-15,229500.0,2414600126,9,2414600126,3.0,1.00,1780.0,7470.0,1.0,...,730.0,1960,0.0,98146,47.5123,-122.337,1780.0,8113.0,0.094028,4
9,2015-03-12,323000.0,3793500160,10,3793500160,3.0,2.50,1890.0,6560.0,2.0,...,0.0,2003,0.0,98038,47.3684,-122.031,2390.0,7570.0,0.383680,3
10,2015-04-03,662500.0,1736800520,11,1736800520,3.0,2.50,3560.0,9796.0,1.0,...,1700.0,1965,0.0,98007,47.6007,-122.145,2210.0,8925.0,0.187181,4
11,2014-05-27,468000.0,9212900260,12,9212900260,2.0,1.00,1160.0,6000.0,1.0,...,300.0,1942,0.0,98115,47.6900,-122.292,1330.0,6000.0,0.092900,5
12,2014-05-28,310000.0,114101516,13,114101516,3.0,1.00,1430.0,19901.0,1.5,...,0.0,1927,NaN,98028,47.7558,-122.229,1780.0,12697.0,0.181686,5
13,2014-10-07,400000.0,6054650070,14,6054650070,3.0,1.75,1370.0,9680.0,1.0,...,0.0,1977,0.0,98074,47.6127,-122.045,1370.0,10208.0,0.287174,10
14,2015-03-12,530000.0,1175000570,15,1175000570,5.0,2.00,1810.0,4850.0,1.5,...,0.0,1900,0.0,98107,47.6700,-122.394,1360.0,4850.0,0.088893,3

In [17]:
#3. compare the housing price between months 
df.groupby("sale_month")["price"].agg(["count", "mean", "median"])

            count           mean    median
sale_month
1             978  525963.251534  438500.0
2            1247  508520.051323  426500.0
3            1875  544057.683200  450000.0
4            2229  562215.615074  477000.0
5            2414  550849.746893  462000.0
6            2178  557534.318182  465000.0
7            2211  544892.161013  465000.0
8            1939  536655.212481  442200.0
9            1771  529723.517787  450000.0
10           1876  539439.447228  447000.0
11           1409  522359.903478  435000.0
12           1470  524799.902041  432500.0

In [18]:
df.describe()

,date,price,house_id,id,id.1,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,sale_month
count,21597,2.159700e+04,2.159700e+04,21597.000000,2.159700e+04,21597.000000,21597.000000,21597.000000,2.159700e+04,21597.000000,...,21597.000000,21145.000000,21597.000000,17749.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000
mean,2014-10-29 04:20:38.171968,5.402966e+05,4.580474e+09,10799.000000,4.580474e+09,3.373200,2.115826,2080.321850,1.509941e+04,1.494096,...,1788.596842,291.857224,1970.999676,836.650516,98077.951845,47.560093,-122.213983,1986.620318,12758.283512,6.573969
min,2014-05-02 00:00:00,7.800000e+04,1.000102e+06,1.000000,1.000102e+06,1.000000,0.500000,370.000000,5.200000e+02,1.000000,...,370.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000,1.000000
25%,2014-07-22 00:00:00,3.220000e+05,2.123049e+09,5400.000000,2.123049e+09,3.000000,1.750000,1430.000000,5.040000e+03,1.000000,...,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471100,-122.328000,1490.000000,5100.000000,4.000000
50%,2014-10-16 00:00:00,4.500000e+05,3.904930e+09,10799.000000,3.904930e+09,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,...,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.231000,1840.000000,7620.000000,6.000000
75%,2015-02-17 00:00:00,6.450000e+05,7.308900e+09,16198.000000,7.308900e+09,4.000000,2.500000,2550.000000,1.068500e+04,2.000000,...,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000,9.000000
max,2015-05-27 00:00:00,7.700000e+06,9.900000e+09,21597.000000,9.900000e+09,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,...,9410.000000,4820.000000,2015.000000,20150.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000,12.000000
std,NaN,3.673681e+05,2.876736e+09,6234.661218,2.876736e+09,0.926299,0.768984,918.106125,4.141264e+04,0.539683,...,827.759761,442.490863,29.375234,4000.110554,53.513072,0.138552,0.140724,685.230472,27274.441950,3.115061

**Data cleaning**

missing data: waterfront, view, sqft_basement, yr_renovated,

In [19]:
# checking details of the house that has 33 rooms 
df[df["bedrooms"] == 33]
# turn out to be outlier

,date,price,house_id,id,id.1,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,sale_month
15856,2014-06-25,640000.0,2402100895,15857,2402100895,33.0,1.75,1620.0,6000.0,1.0,...,1040.0,580.0,1947,0.0,98103,47.6878,-122.331,1330.0,4700.0,6

In [20]:
#deleting the row with 33 rooms

df = df[df["bedrooms"] != 33]

In [21]:
# checking details of the house that has 871200 sqft of lot
df[df["sqft_lot15"] == 871200.0]
# actual house

,date,price,house_id,id,id.1,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,sale_month
9705,2015-01-07,937500.0,225079036,9706,225079036,4.0,4.0,5545.0,871200.0,2.0,...,3605.0,1940.0,2003,0.0,98014,47.676,-121.882,3420.0,871200.0,1

In [47]:
df.describe()

,date,price,house_id,id,id.1,bedrooms,bathrooms,sqft_living,sqft_lot,floors,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,distance_to_downtown,sale_month
count,21597,2.159700e+04,2.159700e+04,21597.000000,2.159700e+04,21597.000000,21597.000000,21597.000000,2.159700e+04,21597.000000,...,21145.000000,21597.000000,17749.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000,21597.000000
mean,2014-10-29 04:20:38.171968,5.402966e+05,4.580474e+09,10799.000000,4.580474e+09,3.373200,2.115826,2080.321850,1.509941e+04,1.494096,...,291.857224,1970.999676,836.650516,98077.951845,47.560093,-122.213983,1986.620318,12758.283512,0.200705,6.573969
min,2014-05-02 00:00:00,7.800000e+04,1.000102e+06,1.000000,1.000102e+06,1.000000,0.500000,370.000000,5.200000e+02,1.000000,...,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000,0.013106,1.000000
25%,2014-07-22 00:00:00,3.220000e+05,2.123049e+09,5400.000000,2.123049e+09,3.000000,1.750000,1430.000000,5.040000e+03,1.000000,...,0.000000,1951.000000,0.000000,98033.000000,47.471100,-122.328000,1490.000000,5100.000000,0.096457,4.000000
50%,2014-10-16 00:00:00,4.500000e+05,3.904930e+09,10799.000000,3.904930e+09,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,...,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.231000,1840.000000,7620.000000,0.178762,6.000000
75%,2015-02-17 00:00:00,6.450000e+05,7.308900e+09,16198.000000,7.308900e+09,4.000000,2.500000,2550.000000,1.068500e+04,2.000000,...,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000,0.284635,9.000000
max,2015-05-27 00:00:00,7.700000e+06,9.900000e+09,21597.000000,9.900000e+09,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,...,4820.000000,2015.000000,20150.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000,1.022692,12.000000
std,NaN,3.673681e+05,2.876736e+09,6234.661218,2.876736e+09,0.926299,0.768984,918.106125,4.141264e+04,0.539683,...,442.490863,29.375234,4000.110554,53.513072,0.138552,0.140724,685.230472,27274.441950,0.121630,3.115061

In [23]:
# checking the list of column

df.columns.tolist()

['date',
 'price',
 'house_id',
 'id',
 'id.1',
 'bedrooms',
 'bathrooms',
 'sqft_living',
 'sqft_lot',
 'floors',
 'waterfront',
 'view',
 'condition',
 'grade',
 'sqft_above',
 'sqft_basement',
 'yr_built',
 'yr_renovated',
 'zipcode',
 'lat',
 'long',
 'sqft_living15',
 'sqft_lot15',
 'sale_month']

In [29]:
df.columns.get_loc("id")

3

In [48]:
#deleting the id column (index n.4)

df = df.drop(df.columns[4], axis=1)

In [51]:
df.head()

,date,price,house_id,id,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15,distance_to_downtown,sale_month
0,2014-10-13,221900.0,7129300520,1,3.0,1.00,1180.0,5650.0,1.0,NaN,...,0.0,1955,0.0,98178,47.5112,-122.257,1340.0,5650.0,0.121099,10
1,2014-12-09,538000.0,6414100192,2,3.0,2.25,2570.0,7242.0,2.0,0.0,...,400.0,1951,19910.0,98125,47.7210,-122.319,1690.0,7639.0,0.115545,12
2,2015-02-25,180000.0,5631500400,3,2.0,1.00,770.0,10000.0,1.0,0.0,...,0.0,1933,NaN,98028,47.7379,-122.233,2720.0,8062.0,0.164820,2
3,2014-12-09,604000.0,2487200875,4,4.0,3.00,1960.0,5000.0,1.0,0.0,...,910.0,1965,0.0,98136,47.5208,-122.393,1360.0,5000.0,0.104890,12
4,2015-02-18,510000.0,1954400510,5,3.0,2.00,1680.0,8080.0,1.0,0.0,...,0.0,1987,0.0,98074,47.6168,-122.045,1800.0,7503.0,0.287296,2

**Dealing with Duplicates**

In [ ]:
#checking duplicate count (row)
df.duplicated().value_counts()

# no duplicates

False    21597
Name: count, dtype: int64

In [ ]:
df.dtypes

# there are no mixed types

date                 str
price            float64
house_id           int64
id                 int64
bedrooms         float64
bathrooms        float64
sqft_living      float64
sqft_lot         float64
floors           float64
waterfront       float64
view             float64
condition          int64
grade              int64
sqft_above       float64
sqft_basement    float64
yr_built           int64
yr_renovated     float64
zipcode            int64
lat              float64
long             float64
sqft_living15    float64
sqft_lot15       float64
dtype: object

In [33]:
#converting date to datetime
df["date"] = pd.to_datetime(df["date"], format="%Y-%m-%d")

In [34]:
#counting missing values per column

df.isna().sum()

date                0
price               0
house_id            0
id                  0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront       2391
view               63
condition           0
grade               0
sqft_above          0
sqft_basement     452
yr_built            0
yr_renovated     3848
zipcode             0
lat                 0
long                0
sqft_living15       0
sqft_lot15          0
dtype: int64

In [35]:
# missing values in waterfront: probably forgot to wrote 0
# before replace the missing cells with 0, I want to compare the housing price to the price of waterfront housing

In [36]:
# 1) Check price stats for houses with missing (NaN) waterfront value
df[df["waterfront"].isna()]["price"].agg(["count", "mean", "median"])

count       2391.000000
mean      528420.124216
median    445000.000000
Name: price, dtype: float64

In [37]:
# 2) Check price stats for houses with waterfront = 1 (has waterfront)
df[df["waterfront"] == 1]["price"].agg(["count", "mean", "median"])

count     1.460000e+02
mean      1.717215e+06
median    1.510000e+06
Name: price, dtype: float64

In [38]:
# 3) Check price stats for houses with waterfront = 0 (no waterfront)
df[df["waterfront"] == 0]["price"].agg(["count", "mean", "median"])

count      19060.000000
mean      532771.208342
median    450000.000000
Name: price, dtype: float64

In [39]:
# All three groups (missing data, waterfront 0/1) together (missing values included as their own group)
df.groupby(df["waterfront"], dropna=False)["price"].agg(["count", "mean", "median"])

            count          mean     median
waterfront
0.0         19060  5.327712e+05   450000.0
1.0           146  1.717215e+06  1510000.0
NaN          2391  5.284201e+05   445000.0

In [40]:
#replacing the empty cell with 0
df = df.fillna({"waterfront": 0})

In [41]:
df["waterfront"].isna().sum()

np.int64(0)

In [42]:
df["view"]

0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
        ...
21592    0.0
21593    0.0
21594    0.0
21595    0.0
21596    0.0
Name: view, Length: 21597, dtype: float64

In [43]:
#replacing the empty cell with 0
#I did not check the mean housing price of these 63 empty cells before filling it up (by accident)
#but I think it will be fine because the number is very small (0.29%)
df = df.fillna({"view": 0})

In [44]:
df["view"].isna().sum()

np.int64(0)

In [45]:
df["sqft_basement"].isna().sum()

np.int64(452)

In [46]:
# does missing data in sqft_basement mean those are houses without basement?
# I want to compare sqft_living vs sqft_above
df[df["sqft_basement"].isna()][["sqft_living", "sqft_above"]].head(452)

       sqft_living  sqft_above
6           1715.0      1715.0
18          1200.0      1200.0
42          3595.0      3595.0
79          3450.0      3450.0
112         1540.0      1160.0
...            ...         ...
21442       2360.0      1390.0
21447       2330.0      2330.0
21473        980.0       980.0
21519       2380.0      2380.0
21581       3410.0      3410.0

[452 rows x 2 columns]

In [47]:
#basement = living sqft - above sqft

df["sqft_basement"] = df["sqft_basement"].fillna(df["sqft_living"] - df["sqft_above"])
df["sqft_basement"].isna().sum()

np.int64(0)

In [48]:
df.isna().sum()

date                0
price               0
house_id            0
id                  0
bedrooms            0
bathrooms           0
sqft_living         0
sqft_lot            0
floors              0
waterfront          0
view                0
condition           0
grade               0
sqft_above          0
sqft_basement       0
yr_built            0
yr_renovated     3848
zipcode             0
lat                 0
long                0
sqft_living15       0
sqft_lot15          0
dtype: int64

In [49]:
df[df["yr_renovated"].isna()]["yr_built"].agg(["count", "mean", "median"])

count     3848.000000
mean      1970.390593
median    1973.000000
Name: yr_built, dtype: float64

In [ ]:
df[df["yr_renovated"].isna()][["yr_renovated", "yr_built", "price"]]

# Initially I thought the houses built in the last 5 years are missing the values in yr_renovated. But it is not the case at all.

       yr_renovated  yr_built      price
2               NaN      1933   180000.0
12              NaN      1927   310000.0
23              NaN      1985   252700.0
26              NaN      1915   937000.0
28              NaN      1948   438000.0
...             ...       ...        ...
21576           NaN      2008   475000.0
21577           NaN      2006  1090000.0
21579           NaN      2006   520000.0
21581           NaN      2007  1580000.0
21583           NaN      2003   810000.0

[3848 rows x 3 columns]

In [ ]:
#I decided that missing value in yr_renovated should be 0, 
# because there could be so many reasons why the history of renovation was not updated. (partial renovation, historical purpose etc.)
# I think keeping the data as 0 is more reasonble than deleting them

#replacing the empty cell with 0

df = df.fillna({"yr_renovated": 0})

In [53]:
df["yr_renovated"].isna().sum()

np.int64(0)